name: heroku-jupyter
dependencies:
  # bind notebook version (compatibility to pgcontents)
  - notebook = 4
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython = 5
  # bind tornado version (websocket problems)
  - tornado = 4.5
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip = 20.1.1
  - pandas = 1.0.1
  - numpy = 1.18.1
  - ltp = 4.0.7
  - lxml = 4.5.2
  - dash = 1.4.1
  - dominate




